### ISSUE TITLE
Issue with the downloader.py file

### ISSUE THREAD

**Issue by VirginieMournetas** [TRoboto/datacamp-downloader#15]
I have followed the README.md protocol.

When I run:

python downloader.py -t TOKEN -l

I get: 

  File "downloader.py", line 39
    output = [*range(int(output[0]), int(output[1]) + 1)]
              ^
SyntaxError: invalid syntax

Thanks for your help.

**Comment by TRoboto** [comment]
Please use the command as follows:
```
python downloader.py -t YOUR_DATACAMP_AUTH_TOKEN -l C
```
where `C` at the end to list your completed courses

**Comment by VirginieMournetas** [comment]
Sadly, I still get the same error.

**Comment by TRoboto** [comment]
Strange! I just tested it and it works. Can you please provide a screenshot of the error showing all the commands you entered? Make sure to blur out your token.

**Comment by VirginieMournetas** [comment]
![error](https://user-images.githubusercontent.com/13849386/88809749-bf2df500-d1b4-11ea-8530-c722e1e9354c.png)

**Comment by VirginieMournetas** [comment]
I finally found out a way to make it work :D

**Comment by TRoboto** [comment]
Oh, it says invalid syntax! I believe this star (unpacking operator) was introduced in python 3. Please make sure you have python 3 installed, you can check the installed version using:
```
python --version
```
Or you can simply remove line 39 from the `downloader.py` file, but note that you cannot use `a-b` next.

Sorry for the misunderstanding, I will point out in the README file that python 3 is required.

**Comment by TRoboto** [comment]
> 
> 
> I finally found out a way to make it work :D

Great to hear this. What was the problem?

**Comment by VirginieMournetas** [comment]
It was an issue with python version, you were right :)

**Comment by TRoboto** [comment]
Awesome! I hope you find this tool useful. 

The README file has been updated accordingly. Thank you for referring to this issue.
