### ISSUE TITLE
Does not show list

### ISSUE THREAD

**Issue by mama1989e** [TRoboto/datacamp-downloader#16]
All i get is:

 HI, (name) 
Active Subscription found 
===================================

but no list of completed tracks or anthing else and i've tried different arguments and cannot get a download started.

**Comment by TRoboto** [comment]
The tool only lists your completed courses.

**Comment by nakami** [comment]
I'm doing a career track, however it consists of multiple courses. Some of said courses, I've already completed.

I can find those courses on https://learn.datacamp.com/courses , e.g. https://learn.datacamp.com/courses/intermediate-python

However, the output of your tool is empty for the following:

```
> python downloader.py -t <SECRET_TOKEN> -l LIST
Hi, Maximilian
Active subscription found
====================================================================================================
```

Better to say, the tool does not finish. I can only kill it via CTRL+C.

Also, this:

```
> python downloader.py -t <SECRET_TOKEN> -l T -a -p dump
Hi, Maximilian
Active subscription found
====================================================================================================
downloader.py:107: DeprecationWarning: isAlive() is deprecated, use is_alive() instead
  while thread.isAlive():
 No completed tracks found!
```

I can provide my token if it helps.

**Comment by nakami** [comment]
See pull request:

- https://github.com/TRoboto/datacamp-downloader/pull/17 "Update README.md" to avoid confusion when reading the call-snippets in the README
- https://github.com/TRoboto/datacamp-downloader/pull/18 "Update downloader.py" to avoid confusion when `-l`/`--list` is called with anything other than `T` or `C`

**Comment by TRoboto** [comment]
Thank you for your contribution. Your pull requests have been merged successfully.
