### ISSUE TITLE
video subtitles

### ISSUE THREAD

**Issue by Vaziri-Mahmoud** [TRoboto/datacamp-downloader#20]
Hi,
Is there any way to download subtitles?

**Comment by TRoboto** [comment]
Hello,
Unfortunately, you cannot at the moment.

**Comment by musmeong** [comment]
We can do it by scraping the transcript below the video. Reference: #23

**Comment by TRoboto** [comment]
@Vaziri-Mahmoud  Check the new version of the tool, subtitles can now be downloaded easily. 
https://github.com/TRoboto/datacamp-downloader

**Comment by TRoboto** [comment]
This issue has been resolved and therefore closed.
