### ISSUE TITLE
It said "No completed courses found!" even if I have completed some courses

### ISSUE THREAD

**Issue by musmeong** [TRoboto/datacamp-downloader#21]
Hi.

I just found that it doesn't work now. I have completed some courses and also I provided correct token and said "Active subscription found", but after that I couldn't find any course. It said "No completed courses found!"

**Comment by TRoboto** [comment]
I updated the tool just now, please try it and send feedback if possible

**Comment by musmeong** [comment]
It works now! Thank you so much.
