### ISSUE TITLE
Python 3.9 AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by tonl** [TRoboto/datacamp-downloader#22]
When I run python downloader.py -t YOUR_DATACAMP_AUTH_TOKEN -l C,
I receive AttributeError: 'Thread' object has no attribute 'isAlive'

I changed isAlive to is_alive on line 115 of downloader.py and everything works.

isAlive is deprecated as of Python 3.9, use is_alive instead.

**Comment by TRoboto** [comment]
Closing this issue since it has been solved.
