### ISSUE TITLE
(Suggestion) Add Transcript Scraper

### ISSUE THREAD

**Issue by musmeong** [TRoboto/datacamp-downloader#23]
We know that Datacamp has new UI and they provide the speaker transcript below the video
![chrome_govZIEsejO](https://user-images.githubusercontent.com/30429518/105627853-d734b780-5e6b-11eb-9db1-d147443e8f8e.jpg)

It will be great if you or anyone can add the feature to scrape the transcript. It will be more helpful for everyone whose main language is not english to understand what the speakers say

**Comment by q-kuwe-w** [comment]
A transcript scraper would definately be a great feature, that is still missing.

**Comment by TRoboto** [comment]
I will soon update the tool to support all new features of Datacamp! Stay tuned!

**Comment by TRoboto** [comment]
@musmeong  @q-kuwe-w   Check the new version of the tool, transcripts can now be downloaded easily. 
https://github.com/TRoboto/datacamp-downloader

**Comment by q-kuwe-w** [comment]
This is awesome!!! THX!

**Comment by TRoboto** [comment]
You are most welcome!

This issue has been resolved and therefore closed.
