### ISSUE TITLE
Exercises don't have instructions, only the script side.

### ISSUE THREAD

**Issue by Yeo987** [TRoboto/datacamp-downloader#25]
In DataCamp Exercises, there are 2 sides, on the left there will be instructions and hints (if used), and the script area on the right. 

The downloaded python files for exercises seem to have only the script side, and not the instructions. Is there a way to get the instructions as well since there usually are some new material not in the lecture videos and the script side written there?

**Comment by TRoboto** [comment]
@Yeo987 Check the new version of the tool. Instructions, hints, codes, solutions, and all things related to the exercises are now included.

**Comment by TRoboto** [comment]
This issue has been resolved and therefore closed.
