### ISSUE TITLE
Unable to download .py files in the current version

### ISSUE THREAD

**Issue by famaouzi** [TRoboto/datacamp-downloader#28]
I remember that I can download .py files (the exercises files that are actually submitted; my own submitted exercises codes) in the previous version. For this newer version, after login I just simply enter `datacamp download all --no-videos` so I can get the data without videos like I previously did, but after checking the downloaded files, there is no single py file at all (there are only .md files) in exercises folders, why? Did I miss something? I rechecked the docs.md but can't find the solution.

**Comment by TRoboto** [comment]
In the previous version, only the code you wrote was downloaded. Now, everything about the exercises gets downloaded as `.md` file including the python code or the solution (the official solution NOT your solution). For example, if you check this [link](https://github.com/TRoboto/Datacamp/blob/master/case-study-school-budgeting-with-machine-learning-in-python/chapter-2-creating-a-simple-first-model/exercises/ex4.md), you will even find the pre-exercise code included.

**Comment by famaouzi** [comment]
Ah, so I can no longer download my own solution, is there a way for the solution to be separated from the file? Better yet if it is my own so it would be familiar to me. I generally used this program so I can review what I've learnt (but forgot) by just files-searching my own codes with *.py filter, the other things in .md are just redundant and making me read it slower. Not sure if others want this but it would be nice if the 'downloading own solution + separate .py files'-feature comes back :)

**Comment by TRoboto** [comment]
This sounds great to me. What do you think of including `--python` option to allow downloading your own solution as a python file?

**Comment by famaouzi** [comment]
That would be nice, thx :)

**Comment by TRoboto** [comment]
This feature has been added. Do you mind testing it and confirming that it works? @famaouzi 

To install the new version, please follow the installation from source steps [here](https://github.com/TRoboto/datacamp-downloader#from-source)

**Comment by famaouzi** [comment]
Yes, it works! I guess I will close this issue then, thx again :)
