### ISSUE TITLE
Can't login to datacamp

### ISSUE THREAD

**Issue by davejal** [TRoboto/datacamp-downloader#35]
Hi,

Whatever I do I can't login. Keeps giving an error that username and password are incorrect. I even changed my password to test it again.

**Comment by davejal** [comment]
This is the response

> WARNING: Couldn't run login with inputs

**Comment by TRoboto** [comment]
This happens to me sometimes due to Cloudflare's protection. Use `set-token` to login, it should work.

**Comment by davejal** [comment]
Thank you, it worked. But now I don't see the courses listed.

**Comment by TRoboto** [comment]
You can only download your completed courses/tracks
