### ISSUE TITLE
it didn't work for me

### ISSUE THREAD

**Issue by kaisgsm011** [TRoboto/datacamp-downloader#5]
it didn't work for me after pasting authentication token nothing happen in the cmd window

**Comment by MuhammadAlBarham** [comment]
Please, can you provide me with a picture of you cmd ( make sure to hide your authentication token, since it private)? 

Thank you!

**Comment by kaisgsm011** [comment]
![Capture](https://user-images.githubusercontent.com/62796094/78657008-10417280-78c0-11ea-8d33-640bbba9c81d.PNG)

**Comment by kaisgsm011** [comment]
![Untitled-1](https://user-images.githubusercontent.com/62796094/78657073-25b69c80-78c0-11ea-9ee4-0d72e4aaf9ff.jpg)

**Comment by kaisgsm011** [comment]
![Untitled-1](https://user-images.githubusercontent.com/62796094/78657163-45e65b80-78c0-11ea-8c03-177ce3aec3ca.png)

**Comment by TRoboto** [comment]
Make sure to get the correct token `_dct` without spaces and put it exactly one space away from `settoken` command. If that doesn't work, please provide us with any error messages you may have received.

**Comment by TRoboto** [comment]
This issue has been closed since we haven't heard from you, but you can open a new issue at any time.
