### ISSUE TITLE
login error 

### ISSUE THREAD

**Issue by iamdouli** [TRoboto/datacamp-downloader#51]
when trying to login with username and password this error occurs "TypeError: expected str, bytes or os.PathLike object, not NoneType". same error occurs when setting token.
![image](https://user-images.githubusercontent.com/57626279/150640882-d27da5c3-2a46-4aba-89d0-ade267d11324.png)

**Comment by TRoboto** [comment]
Does this happen before or after opening the chrome driver?

**Comment by iamdouli** [comment]
never mind, I was not aware the chrome driver, after I installed it worked perfectly fine.
