### ISSUE TITLE
No module named 'datacamp_downloader.templates'

### ISSUE THREAD

**Issue by moziada** [TRoboto/datacamp-downloader#53]
after the installation whenever I try to do any command with datacamp I get this error

![image](https://user-images.githubusercontent.com/60968402/158090628-0612888c-d5c1-4b36-9b00-e24c5b4090e8.png)

**Comment by TRoboto** [comment]
Try to `pip install` in a new virtual environment.

**Comment by moziada** [comment]
> Try to `pip install` in a new virtual environment.

I have manually upgraded urlib3 and some other libraries that shown on the error message, after that I reinstalled datacamp downloader and it worked fine

**Comment by TRoboto** [comment]
Great to hear your issue was resolved.
