### ISSUE TITLE
Downloading w/o completing course 

### ISSUE THREAD

**Issue by acelik** [TRoboto/datacamp-downloader#9]
Hi, No way to download the courses without completing them at first place? I have premium access.

**Comment by MuhammadAlBarham** [comment]
Unfortunately, you cannot. The tool downloads only your completed track(s) or course(s).

**Comment by GhaziXX** [comment]
Hello, @acelik
I made another version of the downloader so you can download the course(s)/track(s) without completing them.
you can take a look here: https://github.com/GhaziXX/datacamp-dl
@MuhammadAlBarham if you want to add the feature I can create a **pull requests**
